version: "3.8"

services:
    telegram-bot:
        build:
            context: telegram-bot
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - API_KEY=${API_KEY}
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
            - MONGO_USER=${MONGO_SPOTIPIE_USER}
            - MONGO_PASSWORD=${MONGO_SPOTIPIE_PASSWORD}
            - MONGO_DB=${MONGO_SPOTIPIE_DB}
            - TEMP_CHANNEL=${TEMP_CHANNEL}
            - REDIRECT_URI=${REDIRECT_URI}
        depends_on:
            mongo:
                condition: service_healthy

    authserver:
        container_name: spotipie-authserver
        restart: unless-stopped
        build:
            context: authserver
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - MONGO_USER=${MONGO_SPOTIPIE_USER}
            - MONGO_PASSWORD=${MONGO_SPOTIPIE_PASSWORD}
            - MONGO_DB=${MONGO_SPOTIPIE_DB}
            - BOT_URL=${BOT_URL}
        ports:
            - 6969:6969
        depends_on:
            mongo:
                condition: service_healthy

    mongo:
        image: bitnami/mongodb:latest
        restart: unless-stopped
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
        environment:
            - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGODB_USERNAME=${MONGO_SPOTIPIE_USER}
            - MONGODB_PASSWORD=${MONGO_SPOTIPIE_PASSWORD}
            - MONGODB_DATABASE=${MONGO_SPOTIPIE_DB}
            - MONGODB_SYSTEM_LOG_VERBOSITY=0

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            # ME_CONFIG_BASICAUTH_USERNAME: admin
            # ME_CONFIG_BASICAUTH_PASSWORD: pass
            # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://root:${MONGO_ROOT_PASSWORD}@mongo:27017/
