version: "3.8"

services:
    telegram-bot:
        build:
            context: telegram-bot
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - API_KEY=${API_KEY}
            - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
            - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
            - MONGO_USR=${MONGO_USR}
            - MONGO_PASS=${MONGO_PASS}
            - MONGO_COLL=${MONGO_COLL}
            - TEMP_CHANNEL=${TEMP_CHANNEL}
            - REDIRECT_URI=${REDIRECT_URI}

    authserver:
        container_name: spotipie-authserver
        restart: unless-stopped
        build:
            context: authserver
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - MONGODB_URI=${MONGODB_URI}
            - MONGODB_URI_LOCAL=${MONGODB_URI_LOCAL}
            - BOT_URL=${BOT_URL}
        ports:
            - 6969:6969
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            # ME_CONFIG_BASICAUTH_USERNAME: admin
            # ME_CONFIG_BASICAUTH_PASSWORD: pass
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ADMIN_USERNAME}:${MONGO_ADMIN_PASSWORD}@mongo:27017/
