version: "3.8"

services:
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
        networks:
            - spotipie

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            # ME_CONFIG_BASICAUTH_USERNAME: admin
            # ME_CONFIG_BASICAUTH_PASSWORD: pass
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ADMIN_USERNAME}:${MONGO_ADMIN_PASSWORD}@mongo:27017/
        networks:
            - spotipie

networks:
    spotipie:
        external: true
