version: "3.7"
services:
    authserver:
        container_name: spotipie-authserver
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - MONGODB_URI=${MONGODB_URI}
            - MONGODB_URI_LOCAL=${MONGODB_URI_LOCAL}
            - BOT_URL=${BOT_URL}
        ports:
            - 6969:6969
        networks:
            - spotipie

networks:
    spotipie:
        external: true
